config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resource :dashboard, only: :index
  resource :feed, only: :show
  resources :users, only: %i[new create]

  get "/signup", to: "users#new", as: :signup

  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create", as: :sessions
  delete "/logout", to: "sessions#destroy", as: :logout

  root to: "dashboard#index"

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/feed.rb
# frozen_string_literal: true

class Feed < ApplicationRecord

  validates :username, presence: true

  def self.recent_entries_for(username:, minutes_ago: 5)
    where(username: username)
      .where("created_at >= ?", minutes_ago.minutes.ago)
      .limit(1)
      .order(created_at: :desc)
      .first
  end

  def self.for_user(username)
    if (recent_entry = recent_entries_for username: username)
      return recent_entry
    end

    # invalidate any old entries
    where(username: username).delete_all

    # query the Twitter API for recent_tweets
    tweets = TwitterAPI.instance.fetch_tweets(username: username)
    tweet_attrs = tweets.map(&:to_h)

    create(username: username, payload: tweet_attrs)
  end

end

app/models/twitter_api.rb
# frozen_string_literal: true

# A singleton facade for the twitter client
class TwitterAPI

  include Singleton

  attr_reader :client

  def initialize
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key = Figaro.env.twitter_consumer_key
      config.consumer_secret = Figaro.env.twitter_consumer_secret
      config.access_token = Figaro.env.twitter_access_token
      config.access_token_secret = Figaro.env.twitter_access_secret
    end
  end

  def fetch_tweets(username:, count: 25)
    client.user_timeline(username, count: count)
  rescue Twitter::Error::Unauthorized, Twitter::Error::NotFound
    []
  end

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord

  validates :email, :name, :password_confirmation, presence: true
  validates :email, uniqueness: { case_sensitive: false }
  validates :email, format: /\A\S+@\S+\.\S+\Z/

  has_secure_password

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end
  helper_method :current_user

  def logged_in?
    current_user.present?
  end
  helper_method :logged_in?

  def authenticate!
    return if logged_in?
    flash[:notice] = "Terribly sorry, would you mind logging in, please?"
    redirect_to login_url
  end

  private

  # Render the current action's template with locals in `values.`
  def locals(values)
    if request.xhr?
      render json: { locals: values }
    else
      render locals: values
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session[:user_id] = nil
  end

end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController

  before_action :authenticate!

  def index
  end

end

app/controllers/feeds_controller.rb
# frozen_string_literal: true

class FeedsController < ApplicationController

  before_action :authenticate!

  def show
    username = params.require(:username)

    feed = Feed.for_user(username)
    tweets = FeedItem.from_list(feed.payload)
    user = tweets&.first&.user&.[]("screen_name") || username

    locals tweets: tweets, user: user
  rescue ActionController::ParameterMissing
    redirect_to root_url, alert: "Please provide a Twitter handle."
  end

end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to root_url, notice: "Welcome, #{user.name}!"
    else
      flash.now[:alert] =
        "Sorry, those credentials aren't quite right. Care to try again?"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to login_url, notice: "Come back soon!"
  end

end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController

  def new
    locals user: User.new
  end

  def create
    user = User.new(user_params)

    if user.save
      log_in(user)
      redirect_to root_url, notice: "Welcome, #{user.name}!"
    else
      render :new,
             locals: { user: user },
             status: :unprocessable_entity
    end
  end

  private

  def user_params
    params
      .require(:user)
      .permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/dashboard/home.html.erb
<h1>tweets!</h1>

<ul>
  <% tweets.each do |tweet| %>
    <li>
      <%= tweet.text %>
      <br>
      <%= tweet.created_at.to_datetime.strftime("%b %-d %Y %l:%M %P") %>
    </li>
  <% end %>
</ul>

app/views/dashboard/index.html.erb
<noscript>
  <%= render "shared/search_form" %>
</noscript>

<div class="row">
  <div class="col-md-7 offset-md-3 js-twitter-search"></div>
</div>

app/views/feeds/show.html.erb
<%= render "shared/search_form" %>

<div class="row">
  <div class="col-md-6 offset-md-3">

    <div class="search-results-header">
      recent tweets by <span class="user-handle"><%= user %></span>
    </div>

    <% if tweets.present? %>
      <ul class="list-group">
        <% tweets.each do |tweet| %>
          <li class="list-group-item">
            <div>
              <%= tweet.body %>
            </div>
            <small class="text-muted">
              <%= tweet.tweet_type %> on <%= tweet.date_posted %>
            </small>
          </li>
        <% end %>
      </ul>
    <% else %>
      No tweets found for that user. Their feed might not be public.
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>windowpane</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "app" %>
    <%= javascript_pack_tag "flash_message" %>

    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">
  </head>

  <body class="container">
    <div class="row">
      <nav class="col-md-7 offset-md-3">
        <ul class="nav justify-content-between">
          <li class="nav-item">
            <%= link_to "windowpane", root_path, class: "nav-link" %>
          </li>

          <% if logged_in? %>
            <li class="nav-item">
              <%= button_to "log out", logout_path,
              { method: :delete,
                class: "remove-button-style",
                form_class: "nav-link"} %>
            </li>
          <% end %>

        </ul>
      </nav>
    </div>

    <div class="row">
      <% unless flash.empty? %>
        <noscript class="col-md-12">
          <div class="col-md-7 offset-md-3">
            <% flash.each do |type, message| %>
              <% alert_type = (type == "alert") ? "danger" : "info" %>
              <div role="alert" class="alert alert-<%= alert_type %>">
                <%= message %>
              </div>
            <% end %>
          </div>
        </noscript>

        <%= content_tag :div,
            role: "alert",
            class: "js-flash-message col-md-7 offset-md-3",
            data: flash.to_a.first.to_json do %>
        <% end %>
      <% end %>
    </div>

    <%= yield %>
  </body>

</html>

app/views/shared/_search_form.html.erb
<div class="row">
  <div class="col-md-7 offset-md-3">
    <form action="<%= feed_path %>"
          method="get">
        <div class="form-group">
          <input name="username"
                 type="text"
                 value=""
                 required="true"
                 placeholder="Let's find some heckin tweets..."
                 class="col-md-8" />

          <input type="submit" value="Search" class="col-md-2" />
        </div>
      </form>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col"></div>
  <div class="col-6 justify-content-center" style="text-align: center">
    <h1>Sign up</h1>

    <%= form_with(model: user, local: true) do |form| %>
      <% if user.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger" role="alert">
            <div>
              <strong>
                <%= pluralize(user.errors.count, "error") %>
                prohibited this user from being saved:
              </strong>
            </div>

            <% user.errors.full_messages.each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>
        </div>
      <% end %>

      <div class="field">
        <%= form.text_field :name,
              id: :user_name,
              placeholder: "Name",
              required: true %>
      </div>
      <div class="field">
        <%= form.text_field :email,
            id: :user_email,
            placeholder: "Email",
            required: true %>
      </div>
      <div class="field">
        <%= form.password_field :password,
            required: true,
            placeholder: "Password" %>
      </div>
      <div class="field">
        <%= form.password_field :password_confirmation,
            required: true,
            placeholder: "Password confirmation" %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>

    <div>
      <%= link_to "Log in", login_path %>
    </div>
  </div>
  <div class="col"></div>
</div>